services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: docker_backend
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - ".env"
    networks:
      - local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 40s
  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crm"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  redis_container:
    image: redis:7
    ports:
      - 6379:6379

  redis_gui:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540


  rabbitmq_container:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  maildev:
      image: maildev/maildev
      ports:
        - "8080:1080"
        - "1025:1025"
      environment:
        - TZ=Asia/Almaty
        - MAILDEV_WEB_PORT=1080
        - MAILDEV_SMTP_PORT=1025
      logging:
        driver: "json-file"
        options:
          max-size: "1m"



volumes:
  rabbitmq-data:
  pg-data:

networks:
  local:
    driver: bridge

