"""empty message

Revision ID: 7044314bf36c
Revises: 9cd536373024
Create Date: 2026-09-04 15:38:44.775951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7044314bf36c'
down_revision: Union[str, Sequence[str], None] = '9cd536373024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('DROP TABLE IF EXISTS deals CASCADE')
    op.execute('DROP TABLE IF EXISTS tasks CASCADE')
    op.execute('DROP TABLE IF EXISTS comments CASCADE')
    op.execute('DROP TABLE IF EXISTS contacts CASCADE')
    op.execute('DROP TABLE IF EXISTS users CASCADE')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('appointed', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deal', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointed'], ['users.user_uuid'], name=op.f('tasks_appointed_fkey')),
    sa.ForeignKeyConstraint(['deal'], ['deals.deal_uuid'], name=op.f('tasks_deal_fkey')),
    sa.PrimaryKeyConstraint('task_uuid', name=op.f('tasks_pkey')),
    sa.UniqueConstraint('title', name=op.f('tasks_title_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('deals',
    sa.Column('deal_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('in_progres', 'expired', 'finished', 'not_started', name='status'), autoincrement=False, nullable=False),
    sa.Column('contact_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_uuid'], ['contacts.contact_uuid'], name=op.f('deals_contact_uuid_fkey')),
    sa.ForeignKeyConstraint(['owner_uuid'], ['users.user_uuid'], name=op.f('deals_owner_uuid_fkey')),
    sa.PrimaryKeyConstraint('deal_uuid', name=op.f('deals_pkey'))
    )
    op.create_table('users',
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('public_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_uuid', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('contacts',
    sa.Column('contact_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('contact_uuid', name=op.f('contacts_pkey')),
    sa.UniqueConstraint('email', name=op.f('contacts_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
