"""empty message

Revision ID: a80a50652ff2
Revises: 7044314bf36c
Create Date: 2026-09-04 15:58:16.271927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a80a50652ff2'
down_revision: Union[str, Sequence[str], None] = '7044314bf36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('contact_uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pipeline_stages',
    sa.Column('stage_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('stage_uuid')
    )
    op.create_table('tg_sessions',
    sa.Column('session_uuid', sa.UUID(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('session_uuid'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('users',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deals',
    sa.Column('deal_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progres', 'expired', 'finished', 'not_started', name='status'), nullable=False),
    sa.Column('contact_uuid', sa.UUID(), nullable=False),
    sa.Column('owner_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_uuid'], ['contacts.contact_uuid'], ),
    sa.ForeignKeyConstraint(['owner_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('deal_uuid')
    )
    op.create_table('notifications',
    sa.Column('notification_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('email', 'telegram', name='notificationtype'), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('notification_uuid')
    )
    op.create_table('revoked_tokens',
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_token_hash'), 'revoked_tokens', ['token_hash'], unique=True)
    op.create_table('comments',
    sa.Column('comment_uuid', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('contact_uuid', sa.UUID(), nullable=True),
    sa.Column('deal_uuid', sa.UUID(), nullable=True),
    sa.Column('author', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['contact_uuid'], ['contacts.contact_uuid'], ),
    sa.ForeignKeyConstraint(['deal_uuid'], ['deals.deal_uuid'], ),
    sa.PrimaryKeyConstraint('comment_uuid')
    )
    op.create_table('tasks',
    sa.Column('task_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointed', sa.UUID(), nullable=False),
    sa.Column('deal', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointed'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['deal'], ['deals.deal_uuid'], ),
    sa.PrimaryKeyConstraint('task_uuid'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('comments')
    op.drop_index(op.f('ix_revoked_tokens_token_hash'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('notifications')
    op.drop_table('deals')
    op.drop_table('users')
    op.drop_table('tg_sessions')
    op.drop_table('pipeline_stages')
    op.drop_table('contacts')
    # ### end Alembic commands ###
