"""empty message

Revision ID: af5a0be73d30
Revises: 5993062b340c
Create Date: 2026-09-04 17:22:54.856510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5a0be73d30'
down_revision: Union[str, Sequence[str], None] = '5993062b340c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'author',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'author',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
